const SHORT_MOVIES_DURATION = 40;
const MIN_BIG_SCREEN_SIZE = 1279;
const MAX_MEDIUM_SCREEN_SIZE = 1280;
const MIN_MEDIUM_SCREEN_SIZE = 767;
const MAX_SMALL_SCREEN_SIZE = 768;
const CARDS_QUANTITY_DECKTOP = 12;
const CARDS_QUANTITY_TABLET = 8;
const CARDS_QUANTITY_MOBILE = 5;
const CARDS_MORE_DECKTOP = 3;
const CARDS_MORE_MOBILE = 2;

export {
  SHORT_MOVIES_DURATION,
  MIN_BIG_SCREEN_SIZE,
  MAX_MEDIUM_SCREEN_SIZE,
  MIN_MEDIUM_SCREEN_SIZE,
  MAX_SMALL_SCREEN_SIZE,
  CARDS_QUANTITY_DECKTOP,
  CARDS_QUANTITY_TABLET,
  CARDS_QUANTITY_MOBILE,
  CARDS_MORE_DECKTOP,
  CARDS_MORE_MOBILE,
};
